site_name: Leo's Lyceum Vault
site_url: https://leo-nakayama.github.io/
theme:
  name: material
  features:
  - navigation.sections
  - navigation.expand
  - toc.integrate
  - content.code.copyk
nav:
- Home: index.md
- Reflective Computing:
  - Overview: reflective-computing/index.md
  - Synthetic Naikan: reflective-computing/synthetic-naikan.md
  - Aristotelian Biodome: reflective-computing/aristotelian-biodome.md
  - Dialectic Modes: reflective-computing/dialectic-modes.md
  - Manifesto: reflective-computing/reflective-computing-manifesto.md
- Projects:
  - Lyceum Workbench: projects/lyceum-workbench.md
  - DSL Inference App: projects/dsl-inference-app.md
- Notes:
<<<<<<< HEAD
  - Console, Terminal, Shell, Job, and Process: docs/notes/console-terminal-shell.md
=======
  - Console, Terminal, Shell, Job, and Process: notes/console-terminal-shell.md
>>>>>>> 9137c72 (Adding new .md files for notes/. Tiding up some markdown mistakes)
  - Create Basic Python Environment: notes/Create-Basic-Python-Environment-then-start-from-red.md
  - Fodeora MAC Address Randomization Issue: notes/Fedora_MAC_Address_Randomization_Issue.md
  - Mermaid Recovery Checklist: notes/mermaid-recovery-checklist.md
  - PreSonus Cancel Guide: notes/presonus-cancel-guide.md
  - Fcitx5 Setup (KDE/Ubuntu): notes/fcitx5-setup.md
  - Fedora Samba Permissions: notes/fedora-samba-permissions.md
  - GitHub Action vs AWS CI/CD: notes/github-actions-vs-aws-cicd.md
- Meta:
  - Content Update Protocol: meta/content-update-protocol.md
markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
extra:
  social:
  - icon: material/github
    link: https://github.com/leo-nakayama/
