site_name: Leo's Lyceum Vault
site_url: https://leo-nakayama.github.io/
theme:
  name: material
  features:
  - navigation.sections
  - navigation.expand
  - toc.integrate
  - content.code.copy
extra_javascript:
  - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
  - js/mermaid-init.js
nav:
- Home: index.md
- Reflective Computing:
  - Overview: reflective-computing/index.md
  - Synthetic Naikan: reflective-computing/synthetic-naikan.md
  - Aristotelian Biodome: reflective-computing/aristotelian-biodome.md
  - Dialectic Modes: reflective-computing/dialectic-modes.md
  - Manifesto: reflective-computing/reflective-computing-manifesto.md
- Projects:
  - Lyceum Workbench: projects/lyceum-workbench.md
  - DSL Inference App: projects/dsl-inference-app.md
- Artifacts:
  - Overview: reflective-computing/artifacts/index.md
  - Reflective Karakuri:
    - Overview: reflective-computing/reflective-karakuri/index.md
    - CFP: reflective-computing/reflective-karakuri/2025-Reflective-Karakuri-CFP.md
    - Observation Report: reflective-computing/reflective-karakuri/2025-Reflective-Karakuri-ObservationReport.md
    - Methodology: reflective-computing/reflective-karakuri/methodology.md
- Notes:
  - Fodeora MAC Address Randomization Issue: notes/Fedora_MAC_Address_Randomization_Issue.md
  - Mermaid Recovery Checklist: notes/mermaid-recovery-checklist.md
  - PreSonus Cancel Guide: notes/presonus-cancel-guide.md
  - Fcitx5 Setup (KDE/Ubuntu): notes/fcitx5-setup.md
  - Fedora Samba Permissions: notes/fedora-samba-permissions.md
  - GitHub Action vs AWS CI/CD: notes/github-actions-vs-aws-cicd.md
- Meta:
  - Content Update Protocol: meta/content-update-protocol.md
markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - fenced_code
  - pymdownx.superfences
extra:
  social:
  - icon: material/github
    link: https://github.com/leo-nakayama/